# Defaults
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Own
safe: true
source: ./
theme: minima


